---

- name: "Install LaTeX packages (minimal)"
  become: true
  apt:
    name: "{{packages}}"
  vars:
    packages:
      - texlive-latex-base
      - texlive-latex-extra
      - texlive-fonts-extra
      - texlive-generic-extra
      - texlive-xetex
      - biber
